// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj5qyjGau4Fckb9CFS0ni9ES-n0de5t6w',
    appId: '1:279262074999:web:770d40b4540cae4cea8e72',
    messagingSenderId: '279262074999',
    projectId: 'da-hood-751b1',
    authDomain: 'da-hood-751b1.firebaseapp.com',
    storageBucket: 'da-hood-751b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdW3D83PW-jWseOHxh_kSmUJk3MVVIRKs',
    appId: '1:279262074999:android:741152e7a55f2131ea8e72',
    messagingSenderId: '279262074999',
    projectId: 'da-hood-751b1',
    storageBucket: 'da-hood-751b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlyYZ08EQTrVCgR2oHFWJNjAvnPLGjD_Q',
    appId: '1:279262074999:ios:f1fd8628d94bf3fbea8e72',
    messagingSenderId: '279262074999',
    projectId: 'da-hood-751b1',
    storageBucket: 'da-hood-751b1.appspot.com',
    iosClientId: '279262074999-h5e91tkma0no1k690qehuc041dl44lsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.daHood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlyYZ08EQTrVCgR2oHFWJNjAvnPLGjD_Q',
    appId: '1:279262074999:ios:f1fd8628d94bf3fbea8e72',
    messagingSenderId: '279262074999',
    projectId: 'da-hood-751b1',
    storageBucket: 'da-hood-751b1.appspot.com',
    iosClientId: '279262074999-h5e91tkma0no1k690qehuc041dl44lsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.daHood',
  );
}
